Crud modalidade
Pecas-Projects/back-atletica pull request #43
Opened 2020-11-17 20:51 UTC by fernandanlisboa

2020-11-17 20:55 UTC, DMCDavi commented on Back-Atletica/Business/Implementação/ModalidadeBusinessImpl.cs
> +            return _ModalidadeRepository.ExcluiModalidade(atleticaModalidadeId);
Eu colocaria o mesmo nome do método

2020-11-17 20:56 UTC, DMCDavi commented on Back-Atletica/Controllers/ModalidadeController.cs
> +        [Route("api/{atleticaId}/Modalidade")]
Porque o id está antes do nome da rota?

2020-11-17 20:57 UTC, DMCDavi commented on Back-Atletica/Controllers/ModalidadeController.cs
> +        [Route("api/{atleticaId}/Modalidade")]
id antes do nome da rota novamente...

2020-11-17 21:00 UTC, DMCDavi commented on Back-Atletica/Repository/Implementação/ModalidadeRepositoryImpl.cs
> +        public HttpRes CriarAtleticaModalidade(AtleticaModalidade modalidade)
Tem certeza de que não precisa de model auxiliar?

2020-11-17 21:07 UTC, DMCDavi commented on Back-Atletica/Repository/Implementação/ModalidadeRepositoryImpl.cs
> +            }
Desnecessário

2020-11-17 21:37 UTC, DMCDavi commented on Back-Atletica/Repository/Implementação/ModalidadeRepositoryImpl.cs
> +                _context.AtleticaModalidades.Remove(modalidadeAtletica);
AtleticaModalidade não pode ser excluída

2020-11-17 21:38 UTC, DMCDavi commented on Back-Atletica/Repository/Implementação/ModalidadeRepositoryImpl.cs
> +        public HttpRes ExcluiModalidade(int atleticaModalidadeId)
AtleticaModalidade não pode ser excluída

2020-11-17 22:19 UTC, fernandanlisboa commented on Back-Atletica/Repository/Implementação/ModalidadeRepositoryImpl.cs
> +        public HttpRes ExcluiModalidade(int atleticaModalidadeId)
É para tirar esse método então @DMCDavi ? Ou apenas suprime a rota dele?

2020-11-18 18:18 UTC, anatartari requested changes

2020-11-18 18:18 UTC, anatartari commented on Back-Atletica/Controllers/ModalidadeController.cs
> +        public IActionResult GetAll(int atleticaId)
Nome pouco intuitivo

2020-11-18 18:18 UTC, anatartari commented on Back-Atletica/Controllers/ModalidadeController.cs
> +            var resultado = _ModalidadeBusiness.CriarAtleticaModalidade(atleticaModalidade);
Transform fora do padrão

2020-11-18 18:18 UTC, anatartari commented on Back-Atletica/Repository/Implementação/ModalidadeRepositoryImpl.cs
> +
Incluir tratamento de erro

2020-11-18 18:18 UTC, anatartari commented on Back-Atletica/Repository/Implementação/ModalidadeRepositoryImpl.cs
> +        }
Faltou tratamento de erro

2020-11-18 18:18 UTC, anatartari commented on Back-Atletica/Utils/RequestModels/ModalidadeModel.cs
> +        }
Retirar parâmetro

2020-11-18 18:18 UTC, anatartari commented on Back-Atletica/Utils/ResponseModels/ModalidadeResponseModels.cs
> +    }
Fazer Classe para AgendaTreino para transformalo em List<>

2020-11-18 18:18 UTC, anatartari commented on Back-Atletica/Repository/Implementação/ModalidadeRepositoryImpl.cs
> +        }
Revisar método para que a tupla sao seja excluído do banco

2020-11-19 17:50 UTC, DMCDavi requested changes

2020-11-19 17:50 UTC, DMCDavi commented on Back-Atletica/Env.cs
> +        public static string ConnString = "User ID = postgres; Password=123456; Host=localhost;Port=5000; Database=Olympos;Pooling=true;Minimum Pool Size=0;Maximum Pool Size=100;";
Só pode ter uma ConnString descomentada, a de Atari ou a sua

2020-11-19 17:50 UTC, DMCDavi commented on Back-Atletica/Repository/Implementação/ModalidadeRepositoryImpl.cs
> +            }
Desnecessário fazer essa verificação, se não houver modalidade da atlética a API vai retornar um array vazio. Colocar isso só diminui a performance.

2020-11-20 19:48 UTC, DMCDavi requested changes

2020-11-20 19:48 UTC, DMCDavi commented on Back-Atletica/Repository/Implementação/ModalidadeRepositoryImpl.cs
> +            Atletica atletica = _context.Atleticas.SingleOrDefault(a => a.AtleticaId == atleticaId);
Nanda, é pra vc tirar essa requisição. O objetivo de eu ter pedido pra vc tirar a verificação era pra vc nn fazer uma requisição desnecessária. Agora essa chamada ao banco ficou ainda mais desnecessária pq vc nn usa essa atletica em lugar nenhum!

2020-11-20 21:54 UTC, fernandanlisboa commented on Back-Atletica/Repository/Implementação/ModalidadeRepositoryImpl.cs
> +            Atletica atletica = _context.Atleticas.SingleOrDefault(a => a.AtleticaId == atleticaId);
Realmente, fui troll demais!

2020-11-23 14:16 UTC, DMCDavi approved these changes

2020-11-23 15:05 UTC, merged