CRUD completo de jogo
Pecas-Projects/back-atletica pull request #51
Opened 2020-11-20 00:02 UTC by DMCDavi

2020-11-23 21:21 UTC, anatartari requested changes

2020-11-23 21:21 UTC, anatartari commented on Back-Atletica/Controllers/JogoController.cs
> +}
O user pode acessar os dados sem que esteja logado ??

2020-11-23 21:21 UTC, anatartari commented on Back-Atletica/Repository/Implementação/JogoRepositoryImpl.cs
> +                }
Dividir o método em funções

2020-11-24 14:29 UTC, DMCDavi commented on Back-Atletica/Controllers/JogoController.cs
> +}
Buscar por atlética e por id são usados no calendário, que pode ser acessado sem login. Já o buscar categorias não tenho certeza se existe alguma tela que o usuário sem login vai utilizar esse método, mas como é apenas um get de categorias de jogo, não vejo motivo em colocar segurança a mais nele. Quer que eu coloque neste?

2020-11-24 19:04 UTC, AmadoMaria approved these changes

2020-11-24 19:07 UTC, merged