CRUD completo de faculdade
Pecas-Projects/back-atletica pull request #55
Opened 2020-11-20 19:30 UTC by DMCDavi

2020-11-23 21:23 UTC, anatartari requested changes

2020-11-23 21:23 UTC, anatartari commented on Back-Atletica/Controllers/FaculdadeController.cs
> +    }
Sem model auxiliar ?

2020-11-24 14:25 UTC, DMCDavi commented on Back-Atletica/Controllers/FaculdadeController.cs
> +    }
A tabela de faculdade só tem id e nome, e é disso que eu preciso. Por qual motivo eu usaria model auxiliar nessa situação??

2020-11-26 21:16 UTC, anatartari commented on Back-Atletica/Controllers/FaculdadeController.cs
> +    }
se nao tiver o model auxiliar vai pegar campos e atletica e por ai vai

2020-11-26 21:40 UTC, DMCDavi commented on Back-Atletica/Controllers/FaculdadeController.cs
> +    }
Só se tivesse include

2020-11-26 21:41 UTC, merged